# Use an official Node.js image as a base
FROM node:16

# Set the working directory
WORKDIR /i211140_frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Install serve to serve the application
RUN npm install -g serve

# Expose the application on port 5678
EXPOSE 1140

# Start the application
CMD ["serve", "-s", "build", "-l", "5678"]
